package loamstream.googlecloud

import loamstream.model.Store
import loamstream.loam.LoamScriptContext
import loamstream.loam.LoamCmdTool
import loamstream.loam.LoamCmdTool.autoGeneratedName
import loamstream.util.BashScript.Implicits._

/**
 * @author clint
 * 2016 or 2017
 */
object GoogleSupport {
  def googleCopy(
      name: String = autoGeneratedName())
      (src: Store, dest: Store, params: String*)(implicit context: LoamScriptContext): Unit = {
    
    import LoamCmdTool._

    val gsutil =  context.googleConfig.gsutilBinary.toAbsolutePath

    cmd"""${gsutil.render} cp ${params.mkString(" ")} ${src} ${dest}"""(name).in(src).out(dest)
  }
}
